/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/swag-lamp.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.r0093.geometry} material={materials.ReflectiveC27D3A} />
      <mesh geometry={nodes.r0096.geometry} material={materials.CartoonFFFFFF} />
      <mesh geometry={nodes.s0099.geometry} material={materials.CartoonFF0A08} />
      <mesh geometry={nodes.s0102Thicken.geometry} material={materials.CartoonFF1100} />
      <mesh geometry={nodes.s0103Thicken.geometry} material={materials.CartoonFF1100} />
      <mesh geometry={nodes.s0104.geometry} material={materials.CartoonFF1100} />
      <mesh geometry={nodes.s0105.geometry} material={materials.CartoonFF1100} />
      <mesh geometry={nodes.s0111.geometry} material={materials.ReflectiveC27D3A} />
    </group>
  )
}

useGLTF.preload('/swag-lamp.gltf')
